#' Get main loadings of the items when estimating an ESEM within cfa model
#'
#' @param latentname a list of latent variable names you would like to choose.
#' @param itemname a list of item name in raw data you would like to use.
#' @param fit an object from the result of lavaan::cfa function.
#'
#' @return a main_load object
#' @export
#'
#' @examples
#' \dontrun{
#' list<-list(c("amo1","amo2","amo3","amo4"),c("ex1","ex2","ex3","ex4"))
#' data2<-read.csv(file="D:/Users/squarrel/rdata/shuju.csv",header=true,sep=",")
#' model1<-'efa("efa")*f1+
#'          efa("efa")*f2=~amo1+amo2+amo3+amo4'
#' fit<-lavaan::cfa(model1,data2)
#' main.load(c("f1","f2"),list,fit)
#' }
main.load<-function(latentname,itemname,fit){
  latentname<-latentname
  itemname<-itemname%>%as.list

  standresoult<-lavaan::standardizedsolution(fit)
  select_load<-standresoult[standresoult$op=="=~",]
  select_load<-dplyr::arrange(select_load,select_load[,c(1,3)])
  a<-select_load[,c(1,3,4,5,7,8,9)]
  nitem<-tidyr::spread(data=select_load[,c(1,3,4)],key="lhs",value='est.std')

  latentrep<-rep(latentname,times=lengths(itemname))
  latentrep<-matrix(latentrep,nrow(nitem),1)
  itemcol<-matrix(nitem[,1],nrow(nitem),1)

  id<-cbind(latentrep,itemcol)
  final_id<-paste(id[,1],id[,2])%>%matrix(nrow(nitem),1)
  new_col<-paste(a$lhs,a$rhs)%>%matrix(nrow(a),1)
  new_a<-cbind(a,new_col)

  load<-new_a%>%dplyr::filter(new_col%in%final_id)
  load1<-dplyr::select(load,-new_col)
  load1<-round(load1[,c(3,4,5,6,7)],digits=3)
  main_load<-cbind(load[,c(1,2)],load1)
  return(main_load)
}

#' A tool to make a confidence interval column
#'
#' @param x an object from the result of get_load function.
#'
#' @return a data.frame
#' @export
#'
ci.col<-function(x){
  fit<-sprintf("[%1.3f, %1.3f]",x$ci.lower,x$ci.upper)%>%data.frame()
  colnames(fit)<-"CI"
  return(fit)
}

#' Get the item names which load onto their priori latent factors depending on the
#' input column numbers in the raw data
#'
#' @param list a list of column numbers indicating the indexes of the items related.
#' @param data the data in which the variable names match the item numbers.
#'
#' @return a list object.
#' @export
#'
#' @examples
#' \dontrun{
#' data2<-read.csv(file="D:/Users/squarrel/rdata/shuju.csv",header=true,sep=",")
#' itemname(list(f1=c(1:4),f2=c(5:8)),data2)
#' }
itemname<-function(list,data){
  latentname=names(list)
  n<-length(latentname)
  for(i in 1:n){
    list[latentname[i]]=list(c(colnames(data[,c(list[[i]])])))
  }
  return(list)
}

#' Get the normal ESEM loading output generated by esemComp::esem_efa function
#'
#'Although ESEM is fundamentally a confirmatory analysis, but we can also do this
#'in an exploratory way.The result of esem_efa function may not give the significant
#'level of item loadings.
#' @param x a object from the result of esemComp::esem_efa function.
#' @return a matrix
#' @export
#'
  esem_load<-function(x){
  load<-x$loadings%>%matrix()

  efa<-matrix(load,nrow(x$loadings),x$factors,byrow=FALSE)
  latent<-rownames(x$loadings)%>%data.frame()
  h2<-x$communality%>%matrix()
  u2<-x$uniquenesses%>%matrix()
  com<-x$complexity%>%matrix()
  esem_load<-cbind(latent,efa,h2,u2,com)

  name<-colnames(x$loadings)

  names(esem_load)<-c("item",name,"h2","u2","com")
  return(esem_load)
}

#' Get standardized loadings
#'
#' @param x an object from lavaan::cfa function.
#'
#' @return a data.frame
#' @export
#'
get_load<-function(x){
  est<-lavaan::standardizedsolution(x)
  fit<-est[est$op=="=~",]
  return(fit)
}
